suppressWarnings(try(data <- expss::apply_labels(data, dcd_correct_detail=c("Yes" = 1,"No" = 0)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, correct_detail=c("Yes" = 1,"No" = 0)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, data_source=c("Deceased’s medical record" = 1,"Hospital Admission Register" = 2,"Ward Register" = 3,"Health facility staff (clinicians/nurses etc)" = 4,"Maternal/Child welfare clinic records" = 5,"Growth Charts" = 6,"Laboratory Results" = 7,"Radiography Results" = 8,"Morgue Register" = 9)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, data_interview=c("Physician" = 1,"Medical Specialist" = 2,"Medical Officer" = 3,"Clinical Officer" = 4,"Nurse" = 5)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, depart_death=c("AE" = 1,"Radiology" = 2,"Medical" = 3,"Paediatric" = 4,"OPD" = 5,"Ward Register MCH/FP" = 6,"Surgical" = 7,"Martenity" = 8,"Gynae" = 9)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, gest37wks=c("Yes" = 1,"No" = 0,"No record" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, asthma=c("Yes" = 1,"No" = 0,"No record" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, lung_tb=c("Yes" = 1,"No" = 0,"No record" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, prior_tb=c("Yes" = 1,"No" = 0,"No record" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, copd=c("Yes" = 1,"No" = 0,"No record" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, home_oxygn_use=c("Yes" = 1,"No" = 0,"No record" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, neuro_disease=c("Yes" = 1,"No" = 0,"No record" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, cva_stroke=c("Yes" = 1,"No" = 0,"No record" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, cancer_h=c("Yes" = 1,"No" = 0,"No record" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, hiv_h=c("Yes" = 1,"No" = 0,"No record" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, chronic_heart=c("Yes" = 1,"No" = 0,"No record" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, heart_failure=c("Yes" = 1,"No" = 0,"No record" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, pacemaker=c("Yes" = 1,"No" = 0,"No record" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, hypertension=c("Yes" = 1,"No" = 0,"No record" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, liver_disease=c("Yes" = 1,"No" = 0,"No record" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, renal_disease=c("Yes" = 1,"No" = 0,"No record" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, dialysis=c("Yes" = 1,"No" = 0,"No record" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, diabetes=c("Yes" = 1,"No" = 0,"No record" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, cerebralpalsy=c("Yes" = 1,"No" = 0,"No record" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, sicklecell=c("Yes" = 1,"No" = 0,"No record" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, malnutrition=c("Yes" = 1,"No" = 0,"No record" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, pepticulcerdisease=c("Yes" = 1,"No" = 0,"No record" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, depression=c("Yes" = 1,"No" = 0,"No record" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, epilepsy=c("Yes" = 1,"No" = 0,"No record" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, alcoholdpndncsyndrome=c("Yes" = 1,"No" = 0,"No record" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, schizophrenia=c("Yes" = 1,"No" = 0,"No record" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, othrmentalhlthllnss=c("Yes" = 1,"No" = 0,"No record" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, lupus_sle=c("Yes" = 1,"No" = 0,"No record" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, goitre=c("Yes" = 1,"No" = 0,"No record" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, thyrotoxicosis=c("Yes" = 1,"No" = 0,"No record" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, congen_malf=c("Yes" = 1,"No" = 0,"No record" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, hiv_infected=c("Yes" = 1,"No" = 0,"NA" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, hiv_regimen=c("1st line" = 1,"2nd line" = 2,"3rd line" = 3,"4th line" = 4,"PMTCT" = 5,"Unknown" = 6)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, anencephaly=c("Yes" = 1,"No" = 0,"No record" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, hydrocephalus=c("Yes" = 1,"No" = 0,"No record" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, microcephaly=c("Yes" = 1,"No" = 0,"No record" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, spinabifida=c("Yes" = 1,"No" = 0,"No record" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, meningomyelocele=c("Yes" = 1,"No" = 0,"No record" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, meningocoele=c("Yes" = 1,"No" = 0,"No record" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, hydrops_swllnbelly=c("Yes" = 1,"No" = 0,"No record" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, gastroschisis=c("Yes" = 1,"No" = 0,"No record" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, cleftlip=c("Yes" = 1,"No" = 0,"No record" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, ambigsgenitalia=c("Yes" = 1,"No" = 0,"No record" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, imperforateanus=c("Yes" = 1,"No" = 0,"No record" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, missinglimbs=c("Yes" = 1,"No" = 0,"No record" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, extradigits=c("Yes" = 1,"No" = 0,"No record" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, othr_defect=c("Yes" = 1,"No" = 0)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, hosplized_lst12=c("Yes" = 1,"No" = 0,"No record" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, recent_diagnosis=c("Pneumonia" = 1,"Malaria" = 2,"PTB" = 3,"HIV/AIDS" = 4,"Gastro Enteritis/ diarrheal Meningitis" = 5,"Acute febrile illness" = 6,"Meningitis" = 7,"Malnutrition" = 8,"Sickle cell" = 9)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, dcd_travell2wks=c("Yes" = 1,"No" = 0,"No record" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, trvel_where=c("Mombasa (County)" = 1,"Kwale" = 2,"Kilifi" = 3,"Tana River" = 4,"Lamu" = 5,"Taita–Taveta" = 6,"Garissa" = 7,"Wajir" = 8,"Mandera" = 9)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, travel_dates_lc=c("Yes" = 1,"No" = 0)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, dcd_outside_2wks=c("Yes" = 1,"No" = 0,"No record" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, travel_dates=c("Yes" = 1,"No" = 0)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, pregnant_dcsed=c("Yes" = 1,"No" = 0,"No record" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, delivered_6wks=c("Yes" = 1,"No" = 0,"No record" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, date6wkdeli=c("Yes" = 1,"No" = 0)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, decsed_smoke=c("Yes" = 1,"No" = 0,"No record" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, smoke_cnsmption=c("Daily" = 1,"Twice" = 2,"Thrice" = 3,"Once" = 4,"No record" = 5)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, sec_smking=c("Yes" = 1,"No" = 0,"No record" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, drink_achol=c("Yes" = 1,"No" = 0,"No record" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, week_alcohol=c("Daily" = 1,"Twice" = 2,"Thrice" = 3,"Once" = 4,"No record" = 5)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, type_alcohol=c("Beer" = 1,"Liquor" = 2,"Local brew" = 3,"Wine" = 4)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, abuse_drugs=c("Yes" = 1,"No" = 0,"No record" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, nmbr_drug_abuse=c("Daily" = 1,"Twice" = 2,"Thrice" = 3,"Once" = 4)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, breast_feeding=c("Yes" = 1,"No" = 0,"No record" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, chld_vaccnated=c("Yes" = 1,"No" = 0,"No record" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, vaccnated_source=c("Vaccination card" = 1,"Clinic records" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, poli_dose1=c("Yes" = 1,"No" = 0,"No record" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, poli_dose2=c("Yes" = 1,"No" = 0,"No record" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, poli_dose3=c("Yes" = 1,"No" = 0,"No record" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, penta_dose1=c("Yes" = 1,"No" = 0,"No record" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, penta_dose2=c("Yes" = 1,"No" = 0,"No record" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, penta_dose3=c("Yes" = 1,"No" = 0,"No record" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, pvc_dose1=c("Yes" = 1,"No" = 0,"No record" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, pvc_dose2=c("Yes" = 1,"No" = 0,"No record" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, pvc_dose3=c("Yes" = 1,"No" = 0,"No record" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, rota_dose1=c("Yes" = 1,"No" = 0,"No record" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, rota_dose2=c("Yes" = 1,"No" = 0,"No record" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, rota_dose3=c("Yes" = 1,"No" = 0,"No record" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, malaria_dose1=c("Yes" = 1,"No" = 0,"No record" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, malaria_dose2=c("Yes" = 1,"No" = 0,"No record" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, malaria_dose3=c("Yes" = 1,"No" = 0,"No record" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, measles_dose1=c("Yes" = 1,"No" = 0,"No record" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, measles_dose2=c("Yes" = 1,"No" = 0,"No record" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, measles_dose3=c("Yes" = 1,"No" = 0,"No record" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, covid_vacc=c("Yes" = 1,"No" = 0,"No record" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, covid_med=c("AstraZenecaOxford" = 1,"PfizerBioNTech" = 2,"Moderna" = 3,"Johnson  Johnson" = 4,"Sinopharm" = 5,"Sputnik" = 6,"Unknown" = 7)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, covid_doses=c("1 dose" = 1,"2 doses" = 2,"Unknown" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, prior_operative=c("Yes" = 1,"No" = 0,"NA" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, know_cmplication=c("Yes" = 1,"No" = 0,"NA" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, prior_complication=c("Fever" = 1,"APH  Antepartum haemorrhage" = 2,"PPH – Postpartum haemorrhage" = 3,"Psychosis" = 4,"Sepsis/septicaemia" = 5,"Pereclampsia/eclampsia" = 6,"Shock" = 7,"Anaemia" = 7,"Gestational Diabetes" = 8)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, hiv_status=c("Positive(+)" = 1,"Negeative()" = 2,"N/A" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, hiv_pmtct=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, art_starte=c("before this pregnancy" = 1,"1 st trimester" = 2,"2 nd trimester" = 3,"3 rd trimester" = 4,"N/A" = 5,"No record" = 6)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, loc_delivery=c("Hospital/health post" = 1,"Home" = 2,"In transit" = 3,"No record" = 4,"N/A" = 5)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, birth_attendant=c("Traditional birth attendant" = 1,"Nurse/Midwife" = 2,"Doctor/Medical Officer" = 3,"Obstetrician" = 4,"No record" = 5,"N/A" = 6)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, delivery_type=c("Vaginal" = 1,"Caeserian" = 2,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, pre_rupture=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, prolng_rupture=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, prolong_labor=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, gestation=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, intra_partum=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, intra_partum_fvr=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, intra_partm_biotic=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, presention=c("Vertex" = 1,"Breech" = 2,"Transverse" = 3,"No record" = 4,"N/A" = 5)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, amniotic_color=c("Clear" = 1,"Purulent" = 2,"Bloody" = 3,"Meconiumstainedthick" = 4,"Meconiumstainedthin" = 5,"Foul smelling" = 6,"No record" = 7,"N/A" = 8)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, spont_move=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, resusc_aft_birth=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, apnoea=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, diff_diagnosis=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, admitted_after=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, admit_conscious=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, mode_arrival=c("Ambulance/EMS" = 1,"POVprivately owned vehicle" = 2,"Bike/Motorbike" = 3,"Public transportation (bus taxi etc)" = 4,"On foot" = 5,"No record" = 6)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, drowning=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, snake_bites=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, poisoning=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, motor_accidnt=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, trauma_event=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, signs_symptms=c("Reported convulsion" = 1,"Chills" = 2,"Lack of appetite" = 3,"Unable to drink or breastfeed at all (For participants 5 ONLY)" = 4,"Skin rash" = 5,"Burns" = 6,"Hives/welts" = 7,"Skin Irritation/pain" = 8,"Skin Itching/pruritus" = 9)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, convulsion=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, skinrash=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, burns=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, hiveswelts=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, skinirritation=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, skinitchingpr=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, erythemaflushi=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, chronicskinul=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, vitiligo=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, fractures=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, boneimplantso=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, redeyes=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, increasedteari=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, eyedischarge=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, painfuleyes=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, yellownessofe=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, hotnessofbody=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, fever=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, hypothermia=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, dizzinessverti=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, fainting=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, irritability=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, lightheadedness=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, lossofbalance=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, memoryloss=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, musclepain=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, musclerigidity=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, muscleweakness=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, paralysis=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, numbnesstingli=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, hypersalivation=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, headache=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, lossofconscio=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, confusion=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, lethargy=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, cough=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, difficultybrea=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, chesttightness=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, hyperventilatio=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, nosebleeding=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, phlegmcongesti=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, wheezing=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, coughingblood=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, stridor=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, sorethroat=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, lossofsmell=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, lossoftaste=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, runnynose=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, earpainordis=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, ringingears=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, chestpain=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, pleuriticchest=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, palpitations=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, sweating=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, fatiguemalaise=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, nausea=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, retching=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, decreasedurine=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, increasedurine=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, painfulmicturi=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, vomiting=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, vomitingblood=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, vomitingyellow=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, vomitinggreen=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, vomitingeveryt=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, diarrheawatery=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, diarrheabloody=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, constipation=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, painfulurinati=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, soremuscles=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, swollenjoints=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, painfulcrisis=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, acutechestsyn=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, unusualbleedin=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, breeding_part=c("Nose" = 1,"Gum" = 2,"Under skin (bruises)" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, seek_outside=c("Yes" = 1,"No" = 0)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, seek_where=c("Health center or dispensary" = 1,"Family friend" = 2,"Pharmacy/chemist" = 3,"Duka/drug seller" = 4,"Herbal Clinic" = 5,"Traditional healer/Spiritual healer" = 6)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, med_hosi=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, med_taken=c("Anticoagulants" = 1,"Antimalarials" = 2,"Antibiotics 1" = 3,"ARVs 1" = 4,"Antivirals (other)" = 5,"AntiTb" = 6,"Antifungals" = 7,"Insulin" = 8,"Oral Hypoglycaemics" = 9)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, anticoagul_route=c("Per Oral (Oral)" = 1,"Intra muscular (IM)" = 2,"Intravenous (IV)" = 3,"Subcutaneous" = 4,"Per rectal (PR)" = 5,"Sub lingual (SL)" = 6,"Topical" = 7,"Intranaval" = 8,"Eye" = 9)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, antimalari_route=c("Per Oral (Oral)" = 1,"Intra muscular (IM)" = 2,"Intravenous (IV)" = 3,"Subcutaneous" = 4,"Per rectal (PR)" = 5,"Sub lingual (SL)" = 6,"Topical" = 7,"Intranaval" = 8,"Eye" = 9)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, antibiotic_name1=c("Amikacin J01GB06" = 1,"Amoxicillin J01CA04" = 2,"Amoxicillin and enzyme inhibitor J01CR02" = 3,"Ampicillin J01CA01" = 4,"Ampicillin and enzyme inhibitor J01CR01" = 5,"Ampicillin combinations J01CA51" = 6,"Aztreonam J01DF01" = 7,"Benzathinebenzylpenicillin J01CE08" = 8,"Azithromycin J01FA10" = 9)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, antibiotic_route1=c("Per Oral (Oral)" = 1,"Intra muscular (IM)" = 2,"Intravenous (IV)" = 3,"Subcutaneous" = 4,"Per rectal (PR)" = 5,"Sub lingual (SL)" = 6,"Topical" = 7,"Intranaval" = 8,"Eye" = 9)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, antibiotic_name2=c("Amikacin J01GB06" = 1,"Amoxicillin J01CA04" = 2,"Amoxicillin and enzyme inhibitor J01CR02" = 3,"Ampicillin J01CA01" = 4,"Ampicillin and enzyme inhibitor J01CR01" = 5,"Ampicillin combinations J01CA51" = 6,"Aztreonam J01DF01" = 7,"Benzathinebenzylpenicillin J01CE08" = 8,"Azithromycin J01FA10" = 9)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, antibiotic_route2=c("Per Oral (Oral)" = 1,"Intra muscular (IM)" = 2,"Intravenous (IV)" = 3,"Subcutaneous" = 4,"Per rectal (PR)" = 5,"Sub lingual (SL)" = 6,"Topical" = 7,"Intranaval" = 8,"Eye" = 9)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, antibiotic_name3=c("Amikacin J01GB06" = 1,"Amoxicillin J01CA04" = 2,"Amoxicillin and enzyme inhibitor J01CR02" = 3,"Ampicillin J01CA01" = 4,"Ampicillin and enzyme inhibitor J01CR01" = 5,"Ampicillin combinations J01CA51" = 6,"Aztreonam J01DF01" = 7,"Benzathinebenzylpenicillin J01CE08" = 8,"Azithromycin J01FA10" = 9)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, antibiotic_route3=c("Per Oral (Oral)" = 1,"Intra muscular (IM)" = 2,"Intravenous (IV)" = 3,"Subcutaneous" = 4,"Per rectal (PR)" = 5,"Sub lingual (SL)" = 6,"Topical" = 7,"Intranaval" = 8,"Eye" = 9)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, antibiotic_name4=c("Amikacin J01GB06" = 1,"Amoxicillin J01CA04" = 2,"Amoxicillin and enzyme inhibitor J01CR02" = 3,"Ampicillin J01CA01" = 4,"Ampicillin and enzyme inhibitor J01CR01" = 5,"Ampicillin combinations J01CA51" = 6,"Aztreonam J01DF01" = 7,"Benzathinebenzylpenicillin J01CE08" = 8,"Azithromycin J01FA10" = 9)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, antibiotic_route4=c("Per Oral (Oral)" = 1,"Intra muscular (IM)" = 2,"Intravenous (IV)" = 3,"Subcutaneous" = 4,"Per rectal (PR)" = 5,"Sub lingual (SL)" = 6,"Topical" = 7,"Intranaval" = 8,"Eye" = 9)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, arvs_name=c("Fuzeon" = 1,"Rukubio" = 2,"Selzentry" = 3,"Trogarzo" = 4,"Isentress" = 5,"Isentress HD" = 6,"Tivicay" = 7,"Vocabria" = 8,"Emtriva" = 9)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, arvs_route=c("Per Oral (Oral)" = 1,"Intra muscular (IM)" = 2,"Intravenous (IV)" = 3,"Subcutaneous" = 4,"Per rectal (PR)" = 5,"Sub lingual (SL)" = 6,"Topical" = 7,"Intranaval" = 8,"Eye" = 9)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, antivirals_name=c("Abacavir" = 1,"Acyclovir (Aciclovir)" = 2,"Adefovir" = 3,"Amantadine" = 4,"Ampligen" = 5,"Amprenavir (Agenerase)" = 6,"Umifenovir (Arbidol)" = 7,"Atazanavir" = 8,"Atripla" = 9)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, antivirals_route=c("Per Oral (Oral)" = 1,"Intra muscular (IM)" = 2,"Intravenous (IV)" = 3,"Subcutaneous" = 4,"Per rectal (PR)" = 5,"Sub lingual (SL)" = 6,"Topical" = 7,"Intranaval" = 8,"Eye" = 9)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, antitb_route=c("Per Oral (Oral)" = 1,"Intra muscular (IM)" = 2,"Intravenous (IV)" = 3,"Subcutaneous" = 4,"Per rectal (PR)" = 5,"Sub lingual (SL)" = 6,"Topical" = 7,"Intranaval" = 8,"Eye" = 9)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, antitb_route1=c("Per Oral (Oral)" = 1,"Intra muscular (IM)" = 2,"Intravenous (IV)" = 3,"Subcutaneous" = 4,"Per rectal (PR)" = 5,"Sub lingual (SL)" = 6,"Topical" = 7,"Intranaval" = 8,"Eye" = 9)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, antitb_route2=c("Per Oral (Oral)" = 1,"Intra muscular (IM)" = 2,"Intravenous (IV)" = 3,"Subcutaneous" = 4,"Per rectal (PR)" = 5,"Sub lingual (SL)" = 6,"Topical" = 7,"Intranaval" = 8,"Eye" = 9)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, antitb_route3=c("Per Oral (Oral)" = 1,"Intra muscular (IM)" = 2,"Intravenous (IV)" = 3,"Subcutaneous" = 4,"Per rectal (PR)" = 5,"Sub lingual (SL)" = 6,"Topical" = 7,"Intranaval" = 8,"Eye" = 9)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, antitb_route4=c("Per Oral (Oral)" = 1,"Intra muscular (IM)" = 2,"Intravenous (IV)" = 3,"Subcutaneous" = 4,"Per rectal (PR)" = 5,"Sub lingual (SL)" = 6,"Topical" = 7,"Intranaval" = 8,"Eye" = 9)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, insulin_route=c("Per Oral (Oral)" = 1,"Intra muscular (IM)" = 2,"Intravenous (IV)" = 3,"Subcutaneous" = 4,"Per rectal (PR)" = 5,"Sub lingual (SL)" = 6,"Topical" = 7,"Intranaval" = 8,"Eye" = 9)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, antifungal_route=c("Per Oral (Oral)" = 1,"Intra muscular (IM)" = 2,"Intravenous (IV)" = 3,"Subcutaneous" = 4,"Per rectal (PR)" = 5,"Sub lingual (SL)" = 6,"Topical" = 7,"Intranaval" = 8,"Eye" = 9)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, oralhypogl_route=c("Per Oral (Oral)" = 1,"Intra muscular (IM)" = 2,"Intravenous (IV)" = 3,"Subcutaneous" = 4,"Per rectal (PR)" = 5,"Sub lingual (SL)" = 6,"Topical" = 7,"Intranaval" = 8,"Eye" = 9)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, oralhypogl_route1=c("Per Oral (Oral)" = 1,"Intra muscular (IM)" = 2,"Intravenous (IV)" = 3,"Subcutaneous" = 4,"Per rectal (PR)" = 5,"Sub lingual (SL)" = 6,"Topical" = 7,"Intranaval" = 8,"Eye" = 9)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, oralhypogl_route2=c("Per Oral (Oral)" = 1,"Intra muscular (IM)" = 2,"Intravenous (IV)" = 3,"Subcutaneous" = 4,"Per rectal (PR)" = 5,"Sub lingual (SL)" = 6,"Topical" = 7,"Intranaval" = 8,"Eye" = 9)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, sedatives_route=c("Per Oral (Oral)" = 1,"Intra muscular (IM)" = 2,"Intravenous (IV)" = 3,"Subcutaneous" = 4,"Per rectal (PR)" = 5,"Sub lingual (SL)" = 6,"Topical" = 7,"Intranaval" = 8,"Eye" = 9)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, steroids_route=c("Per Oral (Oral)" = 1,"Intra muscular (IM)" = 2,"Intravenous (IV)" = 3,"Subcutaneous" = 4,"Per rectal (PR)" = 5,"Sub lingual (SL)" = 6,"Topical" = 7,"Intranaval" = 8,"Eye" = 9)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, immunemodu_route=c("Per Oral (Oral)" = 1,"Intra muscular (IM)" = 2,"Intravenous (IV)" = 3,"Subcutaneous" = 4,"Per rectal (PR)" = 5,"Sub lingual (SL)" = 6,"Topical" = 7,"Intranaval" = 8,"Eye" = 9)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, inotropes_route=c("Per Oral (Oral)" = 1,"Intra muscular (IM)" = 2,"Intravenous (IV)" = 3,"Subcutaneous" = 4,"Per rectal (PR)" = 5,"Sub lingual (SL)" = 6,"Topical" = 7,"Intranaval" = 8,"Eye" = 9)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, antialler_route=c("Per Oral (Oral)" = 1,"Intra muscular (IM)" = 2,"Intravenous (IV)" = 3,"Subcutaneous" = 4,"Per rectal (PR)" = 5,"Sub lingual (SL)" = 6,"Topical" = 7,"Intranaval" = 8,"Eye" = 9)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, antidotes_route=c("Per Oral (Oral)" = 1,"Intra muscular (IM)" = 2,"Intravenous (IV)" = 3,"Subcutaneous" = 4,"Per rectal (PR)" = 5,"Sub lingual (SL)" = 6,"Topical" = 7,"Intranaval" = 8,"Eye" = 9)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, cytotoxics_route=c("Per Oral (Oral)" = 1,"Intra muscular (IM)" = 2,"Intravenous (IV)" = 3,"Subcutaneous" = 4,"Per rectal (PR)" = 5,"Sub lingual (SL)" = 6,"Topical" = 7,"Intranaval" = 8,"Eye" = 9)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, ppis_route=c("Per Oral (Oral)" = 1,"Intra muscular (IM)" = 2,"Intravenous (IV)" = 3,"Subcutaneous" = 4,"Per rectal (PR)" = 5,"Sub lingual (SL)" = 6,"Topical" = 7,"Intranaval" = 8,"Eye" = 9)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, antihypert_route=c("Per Oral (Oral)" = 1,"Intra muscular (IM)" = 2,"Intravenous (IV)" = 3,"Subcutaneous" = 4,"Per rectal (PR)" = 5,"Sub lingual (SL)" = 6,"Topical" = 7,"Intranaval" = 8,"Eye" = 9)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, dmards_route=c("Per Oral (Oral)" = 1,"Intra muscular (IM)" = 2,"Intravenous (IV)" = 3,"Subcutaneous" = 4,"Per rectal (PR)" = 5,"Sub lingual (SL)" = 6,"Topical" = 7,"Intranaval" = 8,"Eye" = 9)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, antipyreti_route=c("Per Oral (Oral)" = 1,"Intra muscular (IM)" = 2,"Intravenous (IV)" = 3,"Subcutaneous" = 4,"Per rectal (PR)" = 5,"Sub lingual (SL)" = 6,"Topical" = 7,"Intranaval" = 8,"Eye" = 9)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, anticonvul_route=c("Per Oral (Oral)" = 1,"Intra muscular (IM)" = 2,"Intravenous (IV)" = 3,"Subcutaneous" = 4,"Per rectal (PR)" = 5,"Sub lingual (SL)" = 6,"Topical" = 7,"Intranaval" = 8,"Eye" = 9)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, oxytocicso_route=c("Per Oral (Oral)" = 1,"Intra muscular (IM)" = 2,"Intravenous (IV)" = 3,"Subcutaneous" = 4,"Per rectal (PR)" = 5,"Sub lingual (SL)" = 6,"Topical" = 7,"Intranaval" = 8,"Eye" = 9)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, tocolytics_route=c("Per Oral (Oral)" = 1,"Intra muscular (IM)" = 2,"Intravenous (IV)" = 3,"Subcutaneous" = 4,"Per rectal (PR)" = 5,"Sub lingual (SL)" = 6,"Topical" = 7,"Intranaval" = 8,"Eye" = 9)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, otherspeci_route=c("Per Oral (Oral)" = 1,"Intra muscular (IM)" = 2,"Intravenous (IV)" = 3,"Subcutaneous" = 4,"Per rectal (PR)" = 5,"Sub lingual (SL)" = 6,"Topical" = 7,"Intranaval" = 8,"Eye" = 9)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, doc_precription=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, clinical_record=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, oxygnation=c("Room air" = 1,"On supplemental Oxygen" = 2,"Mechanical ventilator" = 3,"Not recorded" = 4)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, mental_status=c("Alert/conscious" = 1,"Responds to Voice" = 2,"Responds to Pain" = 3,"Unresponsive" = 4,"No record" = 5)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, lethargic=c("Yes" = 1,"No" = 0)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, convulsioned=c("Yes" = 1,"No" = 0)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, will_admited=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, moni_icu=c("Yes" = 1,"No" = 0)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, nutri_use=c("Well nourished" = 1,"Wasting/Cachexia/marasmus" = 2,"Kwashiorkor" = 3,"Obesity" = 4,"Kwashiorkor" = 5,"No record" = 6)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, growth_charts=c("Normal growth" = 1,"Underweight – low weight for age" = 2,"Stunted – low height for age" = 3,"Wasting – low weight for height" = 4,"Failure to thrive" = 5,"Not applicable" = 6)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, muscle_tone=c("Normal" = 1,"Hypertonia" = 2,"Hypotonia" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, dysmorphicfeat=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, abnormalfacies=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, anteriorfontan=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, evidenceofble=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, scleralicterus=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, bloodinaudito=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, fluidfromthe=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, bulgingerythem=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, nasaldischarge=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, miosis=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, mydriasis=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, exophthalmos=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, enlargedlymph=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, oralthrush=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, hyperaemicinfl=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, respiratorydis=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, ral_crack_fcal=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, ral_crack_diff=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, wheezed=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, stridored=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, nasalflaring=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, lowerchestwal=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, grunting=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, reducedairent=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, tachypnoea=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, cyanosis=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, resp_abnorm=c("None" = 1,"Kussmaul’s/hyperpnoea" = 2,"Agonal/terminal respiration" = 3,"Cheyne stokes" = 4)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, observed_cough=c("None" = 1,"Paroxysmal/whoop" = 2,"Barky" = 3,"No record" = 4)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, abnormalrhythm=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, systolicmurmur=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, diastolicmurmu=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, weakorabsent=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, abdominaldist=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, abdominaltende=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, epigastictende=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, suprapubictend=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, hepatomegaly=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, splenomegaly=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, intraabdominal=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, ascites=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, bowels_movement=c("Normal" = 1,"Increased" = 2,"Decreased" = 3,"Absent" = 4,"No record" = 5)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, undescendedabs=c("Yes" = 1,"No" = 0,"N/A" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, testicularmass=c("Yes" = 1,"No" = 0,"N/A" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, hydrocoele=c("Yes" = 1,"No" = 0,"N/A" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, scrotaltesticu=c("Yes" = 1,"No" = 0,"N/A" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, scrotalpenile=c("Yes" = 1,"No" = 0,"N/A" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, clitoromegaly=c("Yes" = 1,"No" = 0,"N/A" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, bloodtraumain=c("Yes" = 1,"No" = 0,"N/A" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, abnormalityfem=c("Yes" = 1,"No" = 0,"N/A" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, localizedrash=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, generalizedras=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, skinerythema=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, petechiae=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, ecchymosispurp=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, herpeticlesion=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, albinism=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, jaundice=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, bleedingtrauma=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, bleedingfromp=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, bleedingfromu=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, erythemapurule=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, abscess=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, nuchalrigidity=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, photophobia=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, bulgingfontane=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, increasedrefle=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, depressedrefle=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, opisthotonos=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, decorticatepos=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, paralysisd=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, paraplegia=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, quadriplegia=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, monoplegia=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, pupilssize=c("Normal" = 1,"Dilated" = 2,"Pinpoint/constricted" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, pupil_reactivty=c("Normal" = 1,"Fixed" = 2,"Sluggish" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, oedema=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, digitalclubbin=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, jointswelling=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, jointerythema=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, malaria_test_hos=c("Yes" = 1,"No" = 0,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, malaria_yes=c("Rapid test" = 1,"Smear" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, malaria_rapid=c("Positive" = 1,"Negative" = 2,"N/A" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, malaria_smear=c("Positive" = 1,"Negative" = 2,"N/A" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, inpatient_diagnonis=c("Pneumonia" = 1,"Malaria" = 2,"PTB" = 3,"Gastro Enteritis" = 4,"Meningitis" = 5,"Neonatal Sepsis" = 6,"Septicaemia" = 7,"DKA" = 8,"Acute Kidney Injury" = 9)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, haemogramrcd=c("Yes" = 1,"No" = 0,"No record" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, haemogramfull=c("Lowest Hemoglobin level" = 1,"Lowest Hematocrit" = 2,"Red Blood Cell count" = 3,"MCV" = 4,"MCH" = 5,"Erythrocyte sedimentation rate" = 6,"Highest White blood cell count" = 7,"Lowest White blood cell count" = 8,"Neutrophil count" = 9)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, kidney_chemistries=c("Sodium" = 1,"Potassium" = 2,"Chloride" = 3,"Bicarbonate" = 4,"BUN" = 5,"Creatinine" = 6,"Calcium" = 7,"Phosphorus" = 8)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, liver_chemistry=c("AST/SGOT" = 1,"AST/GPT" = 2,"Total bilirubin" = 3,"Direct bilirubin" = 4,"Total Protein" = 5,"Albumin" = 6,"Alkaline phosphatase (ALP)" = 7,"Lactate Dehydrogenase (LDH)" = 8,"Gamma GT" = 9)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, lumbar_puncture=c("Yes" = 1,"No" = 0,"No record" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, lumbar_color=c("Appearance" = 1,"Clear" = 2,"Cloudy" = 3,"Purulent" = 4)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, lumbar_csf=c("Normal" = 1,"Increased" = 2,"Unknown" = 3,"No record" = 4)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, lumbar_india=c("Positive (+)" = 1,"Negative ()" = 2,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, metabolic_screening=c("Yes" = 1,"No" = 0,"No record" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, urine_micro=c("Yes" = 1,"No" = 0,"No record" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, haematuria=c("Yes" = 1,"No" = 0,"No record" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, glycosuria=c("Yes" = 1,"No" = 0,"No record" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, bacteriuria=c("Yes" = 1,"No" = 0,"No record" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, proteinuria=c("Yes" = 1,"No" = 0,"No record" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, nitrites=c("Yes" = 1,"No" = 0,"No record" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, leukocytes=c("Yes" = 1,"No" = 0,"No record" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, dengue_test=c("Yes" = 1,"No" = 0,"No record" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, dengue_result=c("Positive" = 1,"Negative" = 2,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, hiv_test=c("Yes" = 1,"No" = 0,"No record" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, hiv_agab=c("Positive" = 1,"Negative" = 2,"Indetreminate" = 3,"No record" = 4)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, malaria_test=c("Yes" = 1,"No" = 0,"No record" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, malaria_tes_type=c("Rapid/Antigen Test" = 1,"Smear" = 2,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, mala_rapid_rsult=c("Positive" = 1,"Negative" = 2,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, mala_smear_rsult=c("Positive" = 1,"Negative" = 2,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, malaria_speci=c("P falciparum" = 1,"P vivax" = 2,"P ovale" = 3,"P malariae" = 4,"P knowlesi" = 5,"Undetermined species" = 6,"No record" = 7)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, hepatitisa_result=c("Positive" = 1,"Negative" = 2,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, hepatitisb_result=c("Positive" = 1,"Negative" = 2,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, hepatitisc_result=c("Positive" = 1,"Negative" = 2,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, typhoid_result=c("Positive" = 1,"Negative" = 2,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, antibody_test=c("Positive" = 1,"Negative" = 2,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, sickling_test=c("Positive" = 1,"Negative" = 2,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, covid19_test=c("Yes" = 1,"No" = 0,"No record" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, covid19_type=c("COVID19 PCR" = 1,"COVID19 Ag/Ab" = 2,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, covid19_result=c("Positive" = 1,"Negative" = 2,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, covid19_if_no=c("Positive" = 1,"Negative" = 2,"No record" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, radio_imaging=c("Yes" = 1,"No" = 0,"No record" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, skull_xr=c("Normal" = 1,"Abnormal" = 2,"Not Done" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, limb_xr=c("Normal" = 1,"Abnormal" = 2,"Not Done" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, pelvic_xr=c("Normal" = 1,"Abnormal" = 2,"Not Done" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, abd_us=c("Normal" = 1,"Abnormal" = 2,"Not Done" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, pelvic_us=c("Normal" = 1,"Abnormal" = 2,"Not Done" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, obstetric_us=c("Normal" = 1,"Abnormal" = 2,"Not Done" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, fast=c("Normal" = 1,"Abnormal" = 2,"Not Done" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, doppler_u_s=c("Normal" = 1,"Abnormal" = 2,"Not Done" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, paps=c("Normal" = 1,"Abnormal" = 2,"Not Done" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, mammogram=c("Normal" = 1,"Abnormal" = 2,"Not Done" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, ct_chest=c("Normal" = 1,"Abnormal" = 2,"Not Done" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, ct_abd=c("Normal" = 1,"Abnormal" = 2,"Not Done" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, ct_head_brain=c("Normal" = 1,"Abnormal" = 2,"Not Done" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, ctpa=c("Normal" = 1,"Abnormal" = 2,"Not Done" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, hrct=c("Normal" = 1,"Abnormal" = 2,"Not Done" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, mri=c("Normal" = 1,"Abnormal" = 2,"Not Done" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, ecg=c("Normal" = 1,"Abnormal" = 2,"Not Done" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, echo=c("Normal" = 1,"Abnormal" = 2,"Not Done" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, eeg=c("Normal" = 1,"Abnormal" = 2,"Not Done" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, other=c("Normal" = 1,"Abnormal" = 2,"Not Done" = 3)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, icu_patient=c("Yes" = 1,"No" = 0,"No record" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, sup_oxygen=c("Yes" = 1,"No" = 0,"No record" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, mech_vent=c("Yes" = 1,"No" = 0,"No record" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, supplemental_br=c("Yes" = 1,"No" = 0,"No record" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, ng_tube_feeding=c("Yes" = 1,"No" = 0,"No record" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, parenteral_feed=c("Yes" = 1,"No" = 0,"No record" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, blood_transfusi=c("Yes" = 1,"No" = 0,"No record" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, phototherapy_gi=c("Yes" = 1,"No" = 0,"No record" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, hypoglycaemia_t=c("Yes" = 1,"No" = 0,"No record" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, paracentesis_as=c("Yes" = 1,"No" = 0,"No record" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, thoracocentesis=c("Yes" = 1,"No" = 0,"No record" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, pleural_tap=c("Yes" = 1,"No" = 0,"No record" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, craniotomy_burr=c("Yes" = 1,"No" = 0,"No record" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, endoscopy=c("Yes" = 1,"No" = 0,"No record" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, laparotomy=c("Yes" = 1,"No" = 0,"No record" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, suturingmajor=c("Yes" = 1,"No" = 0,"No record" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, suturingminor=c("Yes" = 1,"No" = 0,"No record" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, tracheostomy=c("Yes" = 1,"No" = 0,"No record" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, gastrostomy=c("Yes" = 1,"No" = 0,"No record" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, colostomy=c("Yes" = 1,"No" = 0,"No record" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, dialysis_clin=c("Yes" = 1,"No" = 0,"No record" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, thrombolysis=c("Yes" = 1,"No" = 0,"No record" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, ppn_tpnparente=c("Yes" = 1,"No" = 0,"No record" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, debridement=c("Yes" = 1,"No" = 0,"No record" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, surgical_toilet=c("Yes" = 1,"No" = 0,"No record" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, decontamination=c("Yes" = 1,"No" = 0,"No record" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, gastric_lavage=c("Yes" = 1,"No" = 0,"No record" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, amputation=c("Yes" = 1,"No" = 0,"No record" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, orif_other_otho=c("Yes" = 1,"No" = 0,"No record" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, specialist_consult=c("Yes" = 1,"No" = 0,"No record" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data,   anaesthesiolo=c("Yes" = 1,"No" = 0,"No record" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data,   consultantphy=c("Yes" = 1,"No" = 0,"No record" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data,   ophthalmologi=c("Yes" = 1,"No" = 0,"No record" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data,   entsurgeon=c("Yes" = 1,"No" = 0,"No record" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data,   obstetrician=c("Yes" = 1,"No" = 0,"No record" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data,   haematologist=c("Yes" = 1,"No" = 0,"No record" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data,   paediatrician=c("Yes" = 1,"No" = 0,"No record" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data,   dentist=c("Yes" = 1,"No" = 0,"No record" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data,   physiotherapi=c("Yes" = 1,"No" = 0,"No record" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, gastroenterolog=c("Yes" = 1,"No" = 0,"No record" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, pulmunologist=c("Yes" = 1,"No" = 0,"No record" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, cardiologist=c("Yes" = 1,"No" = 0,"No record" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, surgery=c("Yes" = 1,"No" = 0,"No record" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, infectiousdisea=c("Yes" = 1,"No" = 0,"No record" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, psychiatrist_ps=c("Yes" = 1,"No" = 0,"No record" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, orthopaedic=c("Yes" = 1,"No" = 0,"No record" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, nephrologist=c("Yes" = 1,"No" = 0,"No record" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, neurosurgeon=c("Yes" = 1,"No" = 0,"No record" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, neurologist=c("Yes" = 1,"No" = 0,"No record" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, nutritionist=c("Yes" = 1,"No" = 0,"No record" = 2)), silent=TRUE))
suppressWarnings(try(data <- expss::apply_labels(data, other_specialist=c("Yes" = 1,"No" = 0,"No record" = 2)), silent=TRUE))
